"""Reporter — formats VerdictReports for different output targets.

Supports: terminal (rich), JSON, HTML, and markdown output formats.
"""

from __future__ import annotations

import json
from typing import Any

from verdict.core.types import Category, Severity, VerdictReport


class Reporter:
    """Formats verification reports for display or export."""

    @staticmethod
    def to_json(report: VerdictReport, indent: int = 2) -> str:
        """Export report as JSON."""
        return report.model_dump_json(indent=indent)

    @staticmethod
    def to_dict(report: VerdictReport) -> dict[str, Any]:
        """Export report as a dictionary."""
        return report.model_dump(mode="json")

    @staticmethod
    def to_markdown(report: VerdictReport) -> str:
        """Export report as markdown."""
        lines = [
            f"# Verdict Report: {report.agent_name}",
            "",
            f"**Trace ID:** `{report.trace_id}`",
            f"**Trust Score:** {report.trust_score}/100 ({report.trust_grade})",
            f"**Actions:** {report.total_actions}",
            f"**Checks:** {report.checks_passed} passed / {report.checks_failed} failed / {report.total_checks} total",
            "",
        ]

        if report.critical_findings:
            lines.append("## Critical Findings")
            lines.append("")
            for f in report.critical_findings:
                lines.append(f"- **[{f.severity.value.upper()}]** `{f.check_name}`: {f.message}")
                if f.suggestion:
                    lines.append(f"  - Suggestion: {f.suggestion}")
            lines.append("")

        if report.results:
            lines.append("## All Results")
            lines.append("")
            lines.append("| Check | Category | Severity | Status | Message |")
            lines.append("|-------|----------|----------|--------|---------|")
            for r in report.results:
                status = "PASS" if r.passed else "FAIL"
                lines.append(
                    f"| {r.check_name} | {r.category.value} | {r.severity.value} | {status} | {r.message[:60]} |"
                )
            lines.append("")

        lines.append("---")
        lines.append(f"*Generated by [Verdict](https://verdict.zaphenath.app)*")

        return "\n".join(lines)

    @staticmethod
    def to_terminal(report: VerdictReport) -> str:
        """Format report for terminal output (plain text, no rich dependency)."""
        width = 60
        sep = "=" * width

        lines = [
            sep,
            "  VERDICT REPORT".center(width),
            sep,
            "",
            f"  Agent:       {report.agent_name}",
            f"  Trace:       {report.trace_id}",
            f"  Trust Score: {report.trust_score}/100 ({report.trust_grade})",
            f"  Actions:     {report.total_actions}",
            f"  Checks:      {report.checks_passed}/{report.total_checks} passed",
            "",
        ]

        if report.critical_findings:
            lines.append("-" * width)
            lines.append("  CRITICAL FINDINGS:")
            for f in report.critical_findings:
                lines.append(f"    [{f.severity.value.upper()}] {f.check_name}")
                lines.append(f"      {f.message}")
            lines.append("")

        failed = [r for r in report.results if not r.passed]
        if failed:
            lines.append("-" * width)
            lines.append("  FAILED CHECKS:")
            for r in failed:
                lines.append(f"    [{r.severity.value.upper()}] {r.check_name}: {r.message}")
                if r.suggestion:
                    lines.append(f"      Fix: {r.suggestion}")
            lines.append("")

        lines.append(sep)
        if report.trust_score >= 80 and not report.has_critical():
            lines.append("  VERDICT: APPROVED".center(width))
        else:
            lines.append("  VERDICT: BLOCKED".center(width))
        lines.append(sep)

        return "\n".join(lines)
